import type {Env,Status,Visibility} from './types';
const enc=new TextEncoder(); const json=(data:unknown,status=200,headers:HeadersInit={})=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store',...headers}});
const error=(message:string,status=400)=>json({error:{message}},status);
const now=()=>new Date().toISOString(); const id=()=>crypto.randomUUID();
const hex=(b:ArrayBuffer)=>[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('');
async function digest(s:string){return hex(await crypto.subtle.digest('SHA-256',enc.encode(s)))}
async function validPassword(password:string,stored:string){try{const [salt,it,h]=stored.split(':'); const iterations=Number(it); if(!salt||!it||!h||!Number.isInteger(iterations)||iterations<1||iterations>100000)return false; const key=await crypto.subtle.importKey('raw',enc.encode(password),'PBKDF2',false,['deriveBits']); const out=await crypto.subtle.deriveBits({name:'PBKDF2',hash:'SHA-256',salt:enc.encode(salt),iterations},key,256); const a=new Uint8Array(out),b=new Uint8Array(h.match(/../g)?.map(x=>parseInt(x,16))||[]); if(a.length!==b.length)return false; let d=0; a.forEach((v,i)=>d|=v^b[i]); return d===0}catch(err){console.warn('Password verification failed',err);return false}}
const cookie=(r:Request)=>Object.fromEntries((r.headers.get('cookie')||'').split(';').map(x=>x.trim().split('=')));
async function session(r:Request,e:Env){const token=cookie(r).atelier_session;if(!token)return null;const row=await e.DB.prepare('SELECT csrf_token,expires_at FROM admin_sessions WHERE id_hash=?').bind(await digest(token)).first<{csrf_token:string,expires_at:string}>();return row&&row.expires_at>now()?row:null}
async function guard(r:Request,e:Env){const s=await session(r,e);if(!s)return error('Anmeldung erforderlich.',401);if(!['GET','HEAD'].includes(r.method)&&r.headers.get('x-csrf-token')!==s.csrf_token)return error('Ungültiger CSRF-Schutz.',403);return s}
const clean=(v:unknown,max=5000)=>typeof v==='string'?v.trim().slice(0,max):'';
function artworkInput(v:any){const title=clean(v.title,200);if(!title)throw Error('Ein Titel ist erforderlich.');const status:Status=v.status,visibility:Visibility=v.visibility;if(!['available','reserved','sold'].includes(status)||!['draft','published'].includes(visibility))throw Error('Status oder Sichtbarkeit ist ungültig.');const price=v.price_chf==null||v.price_chf===''?null:Number(v.price_chf);if(price!==null&&(!Number.isInteger(price)||price<0))throw Error('Der Richtpreis muss eine positive ganze CHF-Zahl sein.');return{title,description:clean(v.description),price,status,visibility,sort:Number.isInteger(Number(v.sort_order))?Number(v.sort_order):0}}
async function ensureSiteSections(e:Env){await e.DB.prepare(`CREATE TABLE IF NOT EXISTS site_sections (id INTEGER PRIMARY KEY CHECK(id=1),story_eyebrow TEXT NOT NULL,story_title TEXT NOT NULL,works_eyebrow TEXT NOT NULL,works_title TEXT NOT NULL,works_intro TEXT NOT NULL,contact_eyebrow TEXT NOT NULL,contact_title TEXT NOT NULL,contact_text TEXT NOT NULL,updated_at TEXT NOT NULL)`).run();await e.DB.prepare(`INSERT OR IGNORE INTO site_sections VALUES(1,'Geschichte','Über den Künstler','Werkkatalog','Ausgewählte Werke','Ein persönlicher Einblick in ein künstlerisches Lebenswerk.','Kontakt','Ein Werk berührt Sie?','Gerne geben wir persönlich Auskunft und erzählen Ihnen mehr über die verfügbaren Werke.',?)`).bind(now()).run()}
async function siteData(e:Env){await ensureSiteSections(e);const [base,sections]=await Promise.all([e.DB.prepare('SELECT * FROM site_content WHERE id=1').first<any>(),e.DB.prepare('SELECT * FROM site_sections WHERE id=1').first<any>()]);return{...base,...sections}}
async function publicApi(path:string,e:Env){if(path==='/api/public/site')return json(await siteData(e));if(path==='/api/public/artworks'){const rows=await e.DB.prepare(`SELECT a.*,i.id image_id FROM artworks a LEFT JOIN artwork_images i ON i.artwork_id=a.id AND i.is_primary=1 WHERE a.visibility='published' AND a.deletion_pending=0 ORDER BY a.sort_order,a.created_at DESC`).all();return json(rows.results)}const m=path.match(/^\/api\/public\/artworks\/([^/]+)$/);if(m){const a=await e.DB.prepare(`SELECT * FROM artworks WHERE id=? AND visibility='published' AND deletion_pending=0`).bind(m[1]).first();if(!a)return error('Werk nicht gefunden.',404);const images=await e.DB.prepare('SELECT id,sort_order,is_primary FROM artwork_images WHERE artwork_id=? ORDER BY sort_order').bind(m[1]).all();return json({...a,images:images.results})}return error('Nicht gefunden.',404)}
async function login(r:Request,e:Env){const body:any=await r.json().catch(()=>({}));const client=(r.headers.get('cf-connecting-ip')||'local').slice(0,80), attempt=await e.DB.prepare('SELECT * FROM login_attempts WHERE client_key=?').bind(client).first<any>();if(attempt?.blocked_until>now())return error('Zu viele Versuche. Bitte später erneut versuchen.',429);if(!await validPassword(String(body.password||''),e.ADMIN_PASSWORD_HASH)){const failures=(attempt?.failures||0)+1,blocked=failures>=5?new Date(Date.now()+15*60e3).toISOString():null;await e.DB.prepare(`INSERT INTO login_attempts VALUES(?,?,?,?) ON CONFLICT(client_key) DO UPDATE SET failures=?,blocked_until=?,updated_at=?`).bind(client,failures,blocked,now(),failures,blocked,now()).run();return error('Anmeldedaten sind ungültig.',401)}await e.DB.prepare('DELETE FROM login_attempts WHERE client_key=?').bind(client).run();const token=id()+id(),csrf=id(),expires=new Date(Date.now()+12*3600e3).toISOString();await e.DB.prepare('INSERT INTO admin_sessions VALUES(?,?,?,?)').bind(await digest(token),csrf,expires,now()).run();return json({csrf_token:csrf},200,{'set-cookie':`atelier_session=${token}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=43200`})}
async function adminApi(r:Request,path:string,e:Env){if(path==='/api/admin/login'&&r.method==='POST')return login(r,e);const auth=await guard(r,e);if(auth instanceof Response)return auth;if(path==='/api/admin/session')return json({authenticated:true,csrf_token:auth.csrf_token});if(path==='/api/admin/logout'&&r.method==='POST'){const token=cookie(r).atelier_session;await e.DB.prepare('DELETE FROM admin_sessions WHERE id_hash=?').bind(await digest(token||'')).run();return json({ok:true},200,{'set-cookie':'atelier_session=; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=0'})}
if(path==='/api/admin/artworks'&&r.method==='GET'){const q=new URL(r.url).searchParams.get('q')||'';const rows=await e.DB.prepare(`SELECT * FROM artworks WHERE deletion_pending=0 AND (title LIKE ? OR object_number LIKE ?) ORDER BY sort_order,created_at DESC`).bind(`%${q}%`,`%${q}%`).all();return json(rows.results)}
if(path==='/api/admin/artworks'&&r.method==='POST'){try{const x=artworkInput(await r.json()),aid=id(),t=now();await e.DB.batch([e.DB.prepare('UPDATE object_sequence SET next_number=next_number+1 WHERE id=1'),e.DB.prepare(`INSERT INTO artworks(id,object_number,title,description,price_chf,status,visibility,sort_order,created_at,updated_at) SELECT ?,printf('AT-%03d',next_number-1),?,?,?,?,?,?,?,? FROM object_sequence WHERE id=1`).bind(aid,x.title,x.description,x.price,x.status,x.visibility,x.sort,t,t)]);return json(await e.DB.prepare('SELECT * FROM artworks WHERE id=?').bind(aid).first(),201)}catch(ex){return error(ex instanceof Error?ex.message:'Ungültige Eingabe.')}}
const am=path.match(/^\/api\/admin\/artworks\/([^/]+)$/);if(am&&r.method==='PUT'){try{const x=artworkInput(await r.json());const z=await e.DB.prepare('UPDATE artworks SET title=?,description=?,price_chf=?,status=?,visibility=?,sort_order=?,updated_at=? WHERE id=? AND deletion_pending=0').bind(x.title,x.description,x.price,x.status,x.visibility,x.sort,now(),am[1]).run();return z.meta.changes?json({ok:true}):error('Werk nicht gefunden.',404)}catch(ex){return error(ex instanceof Error?ex.message:'Ungültige Eingabe.')}}
if(am&&r.method==='DELETE'){const imgs=await e.DB.prepare('SELECT r2_key,thumbnail_key FROM artwork_images WHERE artwork_id=?').bind(am[1]).all<any>();await e.DB.prepare('UPDATE artworks SET deletion_pending=1 WHERE id=?').bind(am[1]).run();try{for(const i of imgs.results){await e.IMAGES.delete(i.r2_key);if(i.thumbnail_key)await e.IMAGES.delete(i.thumbnail_key)}await e.DB.prepare('DELETE FROM artworks WHERE id=?').bind(am[1]).run();return json({ok:true})}catch{return error('Löschen vorgemerkt. Bitte erneut versuchen.',503)}}
const upload=path.match(/^\/api\/admin\/artworks\/([^/]+)\/images$/);if(upload&&r.method==='POST'){const a=await e.DB.prepare('SELECT id FROM artworks WHERE id=? AND deletion_pending=0').bind(upload[1]).first();if(!a)return error('Werk nicht gefunden.',404);const form=await r.formData(),file=form.get('image');if(!(file instanceof File))return error('Bild fehlt.');if(file.size>12*1024*1024)return error('Bild ist grösser als 12 MB.',413);const bytes=await file.arrayBuffer(),sig=new Uint8Array(bytes.slice(0,12));let mime='';if(sig[0]===0xff&&sig[1]===0xd8&&sig[2]===0xff)mime='image/jpeg';else if(sig[0]===0x89&&sig[1]===0x50&&sig[2]===0x4e&&sig[3]===0x47)mime='image/png';else if(String.fromCharCode(...sig.slice(0,4))==='RIFF'&&String.fromCharCode(...sig.slice(8,12))==='WEBP')mime='image/webp';else return error('Nur JPEG, PNG und WebP werden unterstützt. HEIC bitte zuerst auf dem Gerät als JPEG exportieren.',415);const iid=id(),key=`artworks/${upload[1]}/${id()}`;await e.IMAGES.put(key,bytes,{httpMetadata:{contentType:mime}});try{const primary=!(await e.DB.prepare('SELECT 1 FROM artwork_images WHERE artwork_id=?').bind(upload[1]).first());await e.DB.prepare('INSERT INTO artwork_images VALUES(?,?,?,?,?,?,?,?,?)').bind(iid,upload[1],key,null,mime,file.size,Number(form.get('sort_order'))||0,primary?1:0,now()).run();return json({id:iid},201)}catch{await e.IMAGES.delete(key);return error('Bild konnte nicht gespeichert werden.',500)}}
const im=path.match(/^\/api\/admin\/images\/([^/]+)$/);if(im&&r.method==='DELETE'){const i=await e.DB.prepare('SELECT * FROM artwork_images WHERE id=?').bind(im[1]).first<any>();if(!i)return error('Bild nicht gefunden.',404);await e.IMAGES.delete(i.r2_key);await e.DB.prepare('DELETE FROM artwork_images WHERE id=?').bind(im[1]).run();return json({ok:true})}
if(path==='/api/admin/site'&&r.method==='GET')return json(await siteData(e));if(path==='/api/admin/site'&&r.method==='PUT'){const b:any=await r.json();const base=[clean(b.artist_name,150),clean(b.hero_title,200),clean(b.intro_text),clean(b.biography,20000),clean(b.contact_name,200),clean(b.email,320),clean(b.phone,80)],sections=[clean(b.story_eyebrow,100),clean(b.story_title,200),clean(b.works_eyebrow,100),clean(b.works_title,200),clean(b.works_intro,1000),clean(b.contact_eyebrow,100),clean(b.contact_title,200),clean(b.contact_text,1000)];if([...base,...sections].some(x=>!x))return error('Alle Website-Felder sind erforderlich.');await ensureSiteSections(e);const t=now();await e.DB.batch([e.DB.prepare('UPDATE site_content SET artist_name=?,hero_title=?,intro_text=?,biography=?,contact_name=?,email=?,phone=?,updated_at=? WHERE id=1').bind(...base,t),e.DB.prepare('UPDATE site_sections SET story_eyebrow=?,story_title=?,works_eyebrow=?,works_title=?,works_intro=?,contact_eyebrow=?,contact_title=?,contact_text=?,updated_at=? WHERE id=1').bind(...sections,t)]);return json({ok:true})}return error('Nicht gefunden.',404)}
async function imageRoute(path:string,e:Env){const iid=path.split('/').pop();const row=await e.DB.prepare(`SELECT i.r2_key,i.mime_type FROM artwork_images i JOIN artworks a ON a.id=i.artwork_id WHERE i.id=? AND a.visibility='published' AND a.deletion_pending=0`).bind(iid).first<any>();if(!row)return error('Bild nicht gefunden.',404);const obj=await e.IMAGES.get(row.r2_key);if(!obj)return error('Bild nicht gefunden.',404);return new Response(obj.body,{headers:{'content-type':row.mime_type,'cache-control':'public,max-age=86400','etag':obj.httpEtag}})}
export default{async fetch(r:Request,e:Env){try{const u=new URL(r.url),p=u.pathname;if(p==='/admin'||p==='/admin/')return e.ASSETS.fetch(new Request(new URL('/admin.html',u),r));if(p.startsWith('/api/public/'))return publicApi(p,e);if(p.startsWith('/api/admin/'))return adminApi(r,p,e);if(p.startsWith('/images/'))return imageRoute(p,e);return e.ASSETS.fetch(r)}catch(err){console.error(err);return error('Ein interner Fehler ist aufgetreten.',500)}}} satisfies ExportedHandler<Env>;
